{{- if and .Values.global.privilegedRights .Values.enableCustomMetrics .Values.APIService .Values.APIService.customMetrics }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  labels:
    app.kubernetes.io/name: v1beta1.custom.metrics.k8s.io
    app.kubernetes.io/instance: v1beta1.custom.metrics.k8s.io
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
spec:
  service:
    name: prometheus-adapter
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
{{- end }}
